---

- name: Check existence of matrix-postgres-backup-s3 service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{matrix_backup_postgres_s3_identifier}}.service"
  register: matrix_postgres_backup_s3_service_stat
  when: "not matrix_backup_postgres_s3_enabled | bool"

- when: matrix_postgres_backup_s3_service_stat.stat.exists | bool
  block:
    - name: Ensure matrix-postgres-backup-s3.timer is stopped
      ansible.builtin.service:
        name: "{{matrix_backup_postgres_s3_identifier}}"
        state: stopped
        enabled: false
        daemon_reload: true
      failed_when: false

    - name: Ensure systemd units don't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ item }}"
        state: absent
      with_items:
        - "{{matrix_backup_postgres_s3_identifier}}.service"
        - "{{matrix_backup_postgres_s3_identifier}}.timer"
